export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  TECHNICIAN = 'TECHNICIAN',
  STORE_PARTNER = 'STORE_PARTNER',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum KycStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ServiceRequestStatus {
  DRAFT = 'DRAFT',
  OPEN_FOR_BIDS = 'OPEN_FOR_BIDS',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum OfferStatus {
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum JobStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  CHANGE_ORDER_PENDING = 'CHANGE_ORDER_PENDING',
  COMPLETED = 'COMPLETED',
  DISPUTE_OPEN = 'DISPUTE_OPEN',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  VOIDED = 'VOIDED',
  REQUIRES_ACTION = 'REQUIRES_ACTION',
}

export enum PaymentMethodType {
  CARD = 'CARD',
  WALLET = 'WALLET',
  VALU = 'VALU',
  INSTALLMENTS = 'INSTALLMENTS',
}

export enum ChangeOrderStatus {
  PROPOSED = 'PROPOSED',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum ChangeOrderType {
  SPARE_PART = 'SPARE_PART',
  EXTRA_LABOR = 'EXTRA_LABOR',
  BOTH = 'BOTH',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED_REFUND_CUSTOMER = 'RESOLVED_REFUND_CUSTOMER',
  RESOLVED_PAY_TECHNICIAN = 'RESOLVED_PAY_TECHNICIAN',
  RESOLVED_SPLIT = 'RESOLVED_SPLIT',
  DISMISSED = 'DISMISSED',
}

export enum StoreOrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  PICKED_UP = 'PICKED_UP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PickupType {
  BRANCH_PICKUP = 'BRANCH_PICKUP',
  DELIVERY = 'DELIVERY',
}

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  PAYMENT_HOLD = 'PAYMENT_HOLD',
  PAYMENT_RELEASE = 'PAYMENT_RELEASE',
  COMMISSION_DEDUCTION = 'COMMISSION_DEDUCTION',
  CHANGE_ORDER_PAYMENT = 'CHANGE_ORDER_PAYMENT',
  WITHDRAWAL = 'WITHDRAWAL',
  REFUND = 'REFUND',
  REWARD_POINTS_CASHBACK = 'REWARD_POINTS_CASHBACK',
}

export enum TransactionDirection {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum SettlementStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  TRANSFERRED = 'TRANSFERRED',
  FAILED = 'FAILED',
  FROZEN_FOR_DISPUTE = 'FROZEN_FOR_DISPUTE',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AntiCircumventionAction {
  NONE = 'NONE',
  BLOCKED = 'BLOCKED',
  WARNING_ISSUED = 'WARNING_ISSUED',
  FLAGGED_FOR_REVIEW = 'FLAGGED_FOR_REVIEW',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
}

export enum DocumentType {
  NATIONAL_ID_FRONT = 'NATIONAL_ID_FRONT',
  NATIONAL_ID_BACK = 'NATIONAL_ID_BACK',
  CRIMINAL_RECORD = 'CRIMINAL_RECORD',
  COMMERCIAL_REGISTER = 'COMMERCIAL_REGISTER',
  TAX_CARD = 'TAX_CARD',
  PROFESSIONAL_LICENSE = 'PROFESSIONAL_LICENSE',
  DISPUTE_EVIDENCE = 'DISPUTE_EVIDENCE',
  SERVICE_PHOTO = 'SERVICE_PHOTO',
  PRODUCT_IMAGE = 'PRODUCT_IMAGE',
}

export enum OtpPurpose {
  REGISTRATION = 'REGISTRATION',
  LOGIN = 'LOGIN',
  ARRIVAL_VERIFICATION = 'ARRIVAL_VERIFICATION',
  COMPLETION_VERIFICATION = 'COMPLETION_VERIFICATION',
  STORE_PICKUP = 'STORE_PICKUP',
}
